README.md, package.json, tools/execute.ts, yarn.lock
This paves the way for getting this code into our build pipeline.
=> Use published sdk

README.md
=> Fix reference to vericode

package.json, tools/copy-dist-files.ts, tools/execute.ts, yarn.lock
This will push out the following changes:
* #17 
* #15 
* #14 
* #13 
* #11
* JPT-1355
Going with a major version change because there are changes to the `_type` values.
=> Release 1.0.0

.gitignore, README.md, docker-compose.sample.yml, docs/jupiterone-io/jupiter-integration-google.md, package.json, tools/execute.ts, yarn.lock
Updates more content from project template, enables local execution without Docker, using .env for environment variables.
The major version bump is due to entity/relationship key value changes, which will lead to deleting all existing data and re-creating it.
=> Release 2.0.0

jest.config.js, package.json, src/converters/UserGroupRelationshipConverter.ts, src/utils/generateKey.ts, test/fixtures/members.json
Once the user things was fixed, this borked the integration.
=> Fix external group member

docs/jupiterone-io/graph-google.md
Update instructions for auth setup.
=> Update auth setup instructions

docs/jupiterone.md
Google has changed their admin console, we need some updates so folks don't get lost.
=> Update docs for the new Google admin console UI

docs/development.md, docs/jupiterone.md
Adopts patterns from https://github.com/JupiterOne/integration-template/pull/22 and captures a bit more detail about exactly what is happening. I'd really like to make this much simpler for our users, but we need a firm understanding of what we have and what is possible before that can happen.
=> Update configuration docs

CHANGELOG.md, package.json, src/steps/groups/index.ts
It's unclear from logs whether the integration is actively processing data or not. This will give more information.
=> Add logging of group processing activity

docs/jupiterone.md
Added in the additional query bullet and documented the list token error found in logs of job events.
=> Add query and list token error

docs/jupiterone.md
=> removed line

CHANGELOG.md, package.json
For role assignments: https://github.com/JupiterOne/graph-google/pull/122
=> Release 3.10.0

docs/jupiterone.md, src/steps/role_assignments/index.ts, src/steps/roles/index.ts, src/steps/tokens/index.ts
- Role and role assignment steps will now catch and report authorization errors the way other steps are handling them.
- Updated documentation listing additional permissions needed to successfully interrogate g sute roles and role assignments.
=> (INTS-107) Handle role and role assignment data ingest failures

CHANGELOG.md, docs/jupiterone.md, src/constants.ts, src/gsuite/clients/GSuiteMobileDeviceClient.ts, src/index.ts, src/steps/mobile_devices/__recordings__/fetchMobileDevices_270458544/recording.har, src/steps/mobile_devices/__snapshots__/converters.test.ts.snap, src/steps/mobile_devices/__snapshots__/index.test.ts.snap, src/steps/mobile_devices/converters.test.ts, src/steps/mobile_devices/converters.ts, src/steps/mobile_devices/index.test.ts, src/steps/mobile_devices/index.ts
Check it out!
We don't actually have any mobile devices in our dev account, so for now, the index.test.ts recording and snapshots are a sham, but the code is there should we need it. I built the converters off of Google's well-typed schema and documentation here:
https://developers.google.com/admin-sdk/directory/v1/guides/manage-mobile-devices
=> Int 2226 ingesting mobile devices

docs/jupiterone.md
=> DOC-50 Update

src/steps/mobile_devices/index.ts, yarn.lock
Catching MDM permission errors and reporting information back to the user.
=> INT-3340 - Catching MDM permission errors

src/gsuite/clients/GSuiteGroupSettingsClient.ts
Handling 401 and 403 errors when accessing group settings.
=> INT-4050 - Handling errors accessing group settings

CHANGELOG.md, docs/jupiterone.md, src/constants.ts, src/gsuite/clients/GSuiteAdminClient.ts, src/gsuite/clients/GSuiteCloudIdentityClient.ts, src/gsuite/clients/GSuiteDeviceClient.ts, src/gsuite/clients/GSuiteDeviceUserClient.ts, src/index.ts, src/steps/account/converters.ts, src/steps/chrome-os-devices/converters.ts, src/steps/chrome-os-devices/index.test.ts, src/steps/domains/converters.ts, src/steps/domains/index.test.ts, src/steps/endpoint-devices/__recordings__/fetchUserDevices_1911469307/recording.har, src/steps/endpoint-devices/__snapshots__/index.test.ts.snap, src/steps/endpoint-devices/converters.ts, src/steps/endpoint-devices/index.test.ts, src/steps/endpoint-devices/index.ts, src/steps/groups/converters.ts, src/steps/groups/index.test.ts, src/steps/mobile_devices/converters.ts, src/steps/mobile_devices/index.test.ts, src/steps/roles/converters.ts, src/steps/roles/index.test.ts, src/steps/tokens/converters.ts
- New entities
| Resources   | Entity `_type`  | Entity `_class` |
| ----------- | --------------- | --------------- |
| Device      | `user_endpoint` | `Device`        |
| Device User | `device_user`   | `User`          |
- New relationships
| Source Entity `_type` | Relationship `_class` | Target Entity `_type`  |
| --------------------- | --------------------- | ---------------------- |
| `google_account`      | **MANAGES**           | `google_user_endpoint` |
| `device_user`         | **IS**  (mapped)               | `google_user`          |
| `device_user`         | **OWNS**              | `user_endpoint`        |
=> INT-2870 - Enhance Google Workspace with Endpoint Management

CHANGELOG.md, src/steps/groups/__snapshots__/index.test.ts.snap, src/steps/users/__snapshots__/converters.test.ts.snap, src/steps/users/converters.ts
- Stopped parsing the username from emails for the following properties on the
`google_user` entity - `username`, `name` and `displayName`.
=> INT-6271 - Stop parsing username from emails

.github/workflows/codeql-analysis.yml
- Run prettier on codeql-analysis.yml file so that the GitHub action pass (needed for NPM release for additional PR).
=> Run prettier on codeql-analysis.yml

.github/workflows/codeql-analysis.yml
Formats codeql-analysis.yml file
=> Format codeql-analysis.yml file

.github/workflows/build.yml, .github/workflows/integration-deployment.yml, .gitignore, CHANGELOG.md, README.md, package.json, yarn.lock
Description: 
Adding changes and new files to incorporate the package build and versioning to npm and raising a PR in integration-deployments to help with workflow efficiency.
=> INT-7812: adding auto package for builds

.github/workflows/integration-deployment.yml
Description: updated version/PR script to use j1/integration-google repo
=> INT-7812: conforming to integration-google repo

CHANGELOG.md, package.json, yarn.lock
Release https://github.com/JupiterOne/vendor-stack/pull/81
=> Upgrade `@jupiterone/vendor-stack`
